---
title: "OKC Project"
author: "Dylan Zumar"
date: "11/05/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r load-libraries}
library("dplyr")
library("ggplot2")
library("broom")
library("knitr")
library("cowplot")
library("readr")
library("arm")
library("olsrr")
library("caret")
library("tidyr")
library("car")
library("ggrepel")
library("infer")
```

```{r data}
all_nba <- read.csv("all-nba-okc-dataset.csv")
glimpse(all_nba)
```


```{r}
all_nba$All.NBA.TEAM.Yes...No = factor(all_nba$All.NBA.TEAM.Yes...No)
levels(all_nba$All.NBA.TEAM.Yes...No)
```


## Mean-Center Variables
```{r}
na_count <-sapply(all_nba, function(y) sum(length(which(is.na(y)))))
na_count <- data.frame(na_count)
na_count

all_nba <- all_nba %>%
  mutate(X3P._Total = if_else(is.na(X3P._Total), 0, X3P._Total)) %>%
  mutate(X3P._Per100 = if_else(is.na(X3P._Per100), 0, X3P._Per100)) %>%
  mutate(X3P._PerGame = if_else(is.na(X3P._Per100), 0, X3P._Per100))

all_nba_mean_centered <- all_nba %>%
  group_by(Year.End) %>%
  mutate(G	= G - mean(G),
         GS = GS - mean(GS),	
         MP_Total	= MP_Total - mean(MP_Total, na.rm=TRUE),
         FG_Total	= FG_Total - mean(FG_Total, na.rm=TRUE),
         FGA_Total	= FGA_Total - mean(FGA_Total, na.rm=TRUE),
         FG._Total	= FG._Total - mean(FG._Total, na.rm=TRUE),
         X3P_Total	= X3P_Total - mean(X3P_Total, na.rm=TRUE),
         X3PA_Total	= X3PA_Total - mean(X3PA_Total, na.rm=TRUE),
         X3P._Total	= X3P._Total - mean(X3P._Total, na.rm=TRUE),
         X2P_Total	= X2P_Total - mean(X2P_Total, na.rm=TRUE),
         X2PA_Total	= X2PA_Total - mean(X2PA_Total, na.rm=TRUE),
         X2P._Total = X2P._Total - mean(X2P._Total, na.rm=TRUE),
         eFG._Total	= eFG._Total - mean(eFG._Total, na.rm=TRUE),
         FT_Total	= FT_Total - mean(FT_Total, na.rm=TRUE),
         FTA_Total = FTA_Total - mean(FTA_Total, na.rm=TRUE),
         FT._Total	= FT._Total - mean(FT._Total, na.rm=TRUE),
         ORB_Total	= ORB_Total - mean(ORB_Total, na.rm=TRUE),
         DRB_Total	= DRB_Total - mean(DRB_Total, na.rm=TRUE),
         TRB_Total	= TRB_Total - mean(TRB_Total, na.rm=TRUE),
         AST_Total	= AST_Total - mean(AST_Total, na.rm=TRUE),
         STL_Total	= STL_Total - mean(STL_Total, na.rm=TRUE),
         BLK_Total	= BLK_Total - mean(BLK_Total, na.rm=TRUE),
         TOV_Total	= TOV_Total - mean(TOV_Total, na.rm=TRUE),
         PF_Total	= PF_Total - mean(PF_Total, na.rm=TRUE),
         PTS_Total	= PTS_Total - mean(PTS_Total, na.rm=TRUE),
         PER_ADV	= PER_ADV - mean(PER_ADV, na.rm=TRUE),
         TS._ADV	= TS._ADV - mean(TS._ADV, na.rm=TRUE),
         X3PAr_ADV	= X3PAr_ADV - mean(X3PAr_ADV, na.rm=TRUE),
         FTr_ADV	= FTr_ADV - mean(FTr_ADV, na.rm=TRUE),
         ORB._ADV	= ORB._ADV - mean(ORB._ADV, na.rm=TRUE),
         DRB._ADV	= DRB._ADV - mean(DRB._ADV, na.rm=TRUE),
         TRB._ADV	= TRB._ADV - mean(TRB._ADV, na.rm=TRUE),
         AST._ADV	= AST._ADV - mean(AST._ADV, na.rm=TRUE),
         STL._ADV	= STL._ADV - mean(STL._ADV, na.rm=TRUE),
         BLK._ADV	= BLK._ADV - mean(BLK._ADV, na.rm=TRUE),
         TOV._ADV	= TOV._ADV - mean(TOV._ADV, na.rm=TRUE),
         USG._ADV	= USG._ADV - mean(USG._ADV, na.rm=TRUE),
         OWS_ADV	= OWS_ADV - mean(OWS_ADV, na.rm=TRUE),
         DWS_ADV	= DWS_ADV - mean(DWS_ADV, na.rm=TRUE),
         WS_ADV	= WS_ADV - mean(WS_ADV, na.rm=TRUE),
         WS.48_ADV	= WS.48_ADV - mean(WS.48_ADV, na.rm=TRUE),
         FG_Per100	= FG_Per100 - mean(FG_Per100, na.rm=TRUE),
         FGA_Per100	= FGA_Per100 - mean(FGA_Per100, na.rm=TRUE),
         FG._Per100	= FG._Per100 - mean(FG._Per100, na.rm=TRUE),
         X3P_Per100	= X3P_Per100 - mean(X3P_Per100, na.rm=TRUE),
         X3PA_Per100	= X3PA_Per100 - mean(X3PA_Per100, na.rm=TRUE),
         X3P._Per100	= X3P._Per100 - mean(X3P._Per100, na.rm=TRUE),
         X2P_Per100	= X2P_Per100 - mean(X2P_Per100, na.rm=TRUE),
         X2PA_Per100	= X2PA_Per100 - mean(X2PA_Per100, na.rm=TRUE),
         X2P._Per100	= X2P._Per100 - mean(X2P._Per100, na.rm=TRUE),
         FT_Per100	= FT_Per100 - mean(FT_Per100, na.rm=TRUE),
         FTA_Per100	= FTA_Per100 - mean(FTA_Per100, na.rm=TRUE),
         FT._Per100	= FT._Per100 - mean(FT._Per100, na.rm=TRUE),
         ORB_Per100	= ORB_Per100 - mean(ORB_Per100, na.rm=TRUE),
         DRB_Per100	= DRB_Per100 - mean(DRB_Per100, na.rm=TRUE),
         TRB_Per100	= TRB_Per100 - mean(TRB_Per100, na.rm=TRUE),
         AST_Per100	= AST_Per100 - mean(AST_Per100, na.rm=TRUE),
         STL_Per100	= STL_Per100 - mean(STL_Per100, na.rm=TRUE),
         BLK_Per100	= BLK_Per100 - mean(BLK_Per100, na.rm=TRUE),
         TOV_Per100	= TOV_Per100 - mean(TOV_Per100, na.rm=TRUE),
         PF_Per100	= PF_Per100 - mean(PF_Per100, na.rm=TRUE),
         PTS_Per100	= PTS_Per100 - mean(PTS_Per100, na.rm=TRUE),
         DRtg_Per100	= DRtg_Per100 - mean(DRtg_Per100, na.rm=TRUE),
         MP_PerGame	= MP_PerGame - mean(MP_PerGame, na.rm=TRUE),
         FG_PerGame	= FG_PerGame - mean(FG_PerGame, na.rm=TRUE),
         FGA_PerGame	= FGA_PerGame - mean(FGA_PerGame, na.rm=TRUE),
         FG._PerGame	= FG._PerGame - mean(FG._PerGame, na.rm=TRUE),
         X3P_PerGame	= X3P_PerGame - mean(X3P_PerGame, na.rm=TRUE),
         X3PA_PerGame= X3PA_PerGame - mean(X3PA_PerGame, na.rm=TRUE),	
         X3P._PerGame= X3P._PerGame - mean(X3P._PerGame, na.rm=TRUE),	
         X2P_PerGame	= X2P_PerGame - mean(X2P_PerGame, na.rm=TRUE),
         X2PA_PerGame= X2PA_PerGame - mean(X2PA_PerGame, na.rm=TRUE),	
         X2P._PerGame	= X2P._PerGame - mean(X2P._PerGame, na.rm=TRUE),
         eFG._PerGame	= eFG._PerGame - mean(eFG._PerGame, na.rm=TRUE),
         FT_PerGame	= FT_PerGame - mean(FT_PerGame, na.rm=TRUE),
         FTA_PerGame	= FTA_PerGame - mean(FTA_PerGame, na.rm=TRUE),
         FT._PerGame	= FT._PerGame - mean(FT._PerGame, na.rm=TRUE),
         ORB_PerGame	= ORB_PerGame - mean(ORB_PerGame, na.rm=TRUE),
         DRB_PerGame	= DRB_PerGame - mean(DRB_PerGame, na.rm=TRUE),
         TRB_PerGame	= TRB_PerGame - mean(TRB_PerGame, na.rm=TRUE),
         AST_PerGame	= AST_PerGame - mean(AST_PerGame, na.rm=TRUE),
         STL_PerGame	= STL_PerGame - mean(STL_PerGame, na.rm=TRUE),
         BLK_PerGame	= BLK_PerGame - mean(BLK_PerGame, na.rm=TRUE),
         TOV_PerGame	= TOV_PerGame - mean(TOV_PerGame, na.rm=TRUE),
         PF_PerGame	= PF_PerGame - mean(PF_PerGame, na.rm=TRUE),
         PS.G_PerGame= PS.G_PerGame - mean(PS.G_PerGame, na.rm=TRUE))

all_nba_mean_centered_no_NA <- all_nba_mean_centered %>%
  dplyr::select(-OBPM_ADV,-DBPM_ADV,-BPM_ADV,-VORP_ADV,-ORtg_Per100) %>%
  na.omit()
```

##Check Dataset
```{r}
all_nba_mean_centered_no_NA %>%
  group_by(Year.End) %>%
  count(All.NBA.TEAM.Yes...No)
```

##Finalize Dataset, Remove Highly Correlated Variables
```{r}
test<- all_nba_mean_centered_no_NA %>%
  ungroup() %>%
  dplyr::select(-Player,-Tm,-Year.End,-Pos,-Pos_Rev,-All.NBA.TEAM.Yes...No,-All.NBA.Team,-Prev_Count)

remove <- findCorrelation(cor(test), cutoff = .8, verbose = TRUE, names = TRUE)
new_test <- test %>%
  dplyr::select(-remove)
component1 <- all_nba_mean_centered_no_NA %>%
  dplyr::select(ID,Player,Tm,Pos,Pos_Rev,All.NBA.TEAM.Yes...No,All.NBA.Team,Prev_Count)

final_data <- merge(component1,new_test, by="ID")
```

##Test Time Series
```{r}
final_data <- final_data %>%
  group_by(Player)
A <- final_data %>%
  ggplot(mapping = aes(x = Year.End, y = All_NBA_Count)) +
  geom_line()
B <- final_data %>%
  group_by(Player) %>%
  ggplot(mapping = aes(x = Year.End, y = All_NBA_Count)) +
  geom_line()
C <- final_data %>%
  group_by(Player) %>%
  ggplot(mapping = aes(x = Year.End, y = All_NBA_Count)) +
  geom_line()
pacf(final_data$All_NBA_Count)
plot_grid(A,B,C)
final_data <- final_data %>%
  ungroup()
```

##Create full model, do backward selection
```{r}
full_model <- glm(All_NBA_Count ~ Age +
          G+
          GS +
          PER_ADV +
          X3PAr_ADV + 
          FTr_ADV+
          DRB._ADV+
          TOV._ADV+
          WS_ADV+
          WS.48_ADV+
          FGA_Per100+
          X2PA_Per100+
          FTA_Per100+
          ORB_Per100+
          AST_Per100+
          STL_Per100+
          BLK_Per100+
          TOV_Per100+
          PF_Per100+
          DRtg_Per100+
          X3P._PerGame+
          FT._PerGame+
          ORB_PerGame+
          STL_PerGame+
          BLK_PerGame+
          TOV_PerGame+
          Prev_Count +
          PF_PerGame
           , family=poisson,data=final_data)
AIC(full_model)
step(full_model)
```
##Limit multicollinearity
```{r}
stepped_model <- glm(formula = All_NBA_Count ~ Age + G + GS + PER_ADV + X3PAr_ADV + 
    DRB._ADV + TOV._ADV + WS_ADV + FGA_Per100 + X2PA_Per100 + 
    FTA_Per100 + ORB_Per100 + AST_Per100 + STL_Per100 + BLK_Per100 + 
    PF_Per100 + DRtg_Per100 + X3P._PerGame + FT._PerGame + ORB_PerGame + 
    STL_PerGame + TOV_PerGame + Prev_Count + PF_PerGame, family = poisson, 
    data = final_data)
tidy(vif(stepped_model))
```

X3PAr_ADV, -----FGA_Per100, X2PA_Per100, ORB_Per100, ----ORB_PerGame, ----STL_PerGame


```{r}
base_model_test <- glm(formula = All_NBA_Count ~ Age + G + GS + PER_ADV + X3PAr_ADV + 
    DRB._ADV + TOV._ADV + WS_ADV + X2PA_Per100 + 
    FTA_Per100 + ORB_Per100 + AST_Per100 + STL_Per100 + BLK_Per100 + 
    PF_Per100 + DRtg_Per100 + X3P._PerGame + FT._PerGame + TOV_PerGame + Prev_Count + PF_PerGame, family = poisson, 
    data = final_data)
tidy(vif(base_model))
```


```{r}
base_model <- glm(formula = All_NBA_Count ~ Age + G + GS + PER_ADV + X3PAr_ADV + 
    DRB._ADV + TOV._ADV + WS_ADV + X2PA_Per100 + 
    FTA_Per100 + ORB_Per100 + AST_Per100 + STL_Per100 + BLK_Per100 + 
    PF_Per100 + DRtg_Per100 + X3P._PerGame + FT._PerGame + TOV_PerGame + Prev_Count + PF_PerGame, family = poisson, 
    data = final_data)
tidy(vif(base_model))
AIC(base_model)
```

##Find Interactions
```{r}
base_model_interaction <- glm(formula = All_NBA_Count ~ Age + G + GS + PER_ADV + X3PAr_ADV + 
    DRB._ADV + TOV._ADV + WS_ADV + X2PA_Per100 + 
    FTA_Per100 + ORB_Per100 + AST_Per100 + STL_Per100 + BLK_Per100 + 
    PF_Per100 + DRtg_Per100 + X3P._PerGame + FT._PerGame + TOV_PerGame + Prev_Count + PF_PerGame + Age*AST_Per100, family = poisson, data = final_data)
kable(anova(base_model,base_model_interaction,test="Chisq"),format="html")
```

##Final Model

```{r}
final_model <- glm(formula = All_NBA_Count ~ Age + G + GS + PER_ADV + X3PAr_ADV + 
    DRB._ADV + TOV._ADV + WS_ADV + X2PA_Per100 + 
    FTA_Per100 + ORB_Per100 + AST_Per100 + STL_Per100 + BLK_Per100 + 
    PF_Per100 + DRtg_Per100 + X3P._PerGame + FT._PerGame + TOV_PerGame + Prev_Count + PF_PerGame + Age*AST_Per100, family = poisson, data = final_data)
```


##Residuals/Predicted

```{r}
final_data <- final_data %>%
  mutate(predicted = predict(final_model, type = "response")) %>%
  mutate(residuals = residuals(final_model, type="pearson"))

final_data %>%
  ggplot(mapping = aes(x = predicted, y = residuals)) +
  geom_point()
```


```{r}
final_data %>%
  ggplot(mapping = aes(x = Age, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = G, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = GS, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = PER_ADV, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = X3PAr_ADV, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = DRB._ADV, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = TOV._ADV, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = WS_ADV, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = X2PA_Per100, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = ORB_Per100, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = FTA_Per100, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = AST_Per100, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = STL_Per100, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = BLK_Per100, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = PF_Per100, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = DRtg_Per100, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = X3P._PerGame, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = FT._PerGame, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = TOV_PerGame, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = Prev_Count, y = residuals)) +
  geom_point()
final_data %>%
  ggplot(mapping = aes(x = PF_PerGame, y = residuals)) +
  geom_point()
```

```{r}
final_data %>%
  ggplot(mapping = aes(y = Age)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = GS)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = PER_ADV)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = X3PAr_ADV)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = FTr_ADV)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = DRB._ADV)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = TOV._ADV)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = WS_ADV)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = WS.48_ADV)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = X2PA_Per100)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = ORB_Per100)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = AST_Per100)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = STL_Per100)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = BLK_Per100)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = PF_Per100)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = DRtg_Per100)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = FT._PerGame)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = Prev_Count)) +
  geom_boxplot()
final_data %>%
  ggplot(mapping = aes(y = PF_PerGame)) +
  geom_boxplot()
```

##Visualization

```{r}
all_nba %>%
  summarise(mean = mean(GS))
plot <- final_data %>%
  group_by(Year.End) %>%
  arrange(desc(predicted)) %>%
  slice(1:15) %>%
  group_by(Year.End, All.NBA.TEAM.Yes...No) %>%
  summarise(counts = n())
plot %>%
  group_by(Year.End) %>%
  mutate(percent = 100*(counts/15)) %>%
  ggplot(mapping = aes(x = Year.End, y = percent, fill = All.NBA.TEAM.Yes...No)) +
  geom_bar(width = 0.8, stat = "identity", position = "stack") +
  ggtitle("Proportion of All-NBA Selections in a Given Year Predicted by Model") +
 labs(subtitle = "Based on Highest 15 Predicted All-NBA Selections", y = "Percentage that Made All-NBA (%)", x = "Year", fill = "Made All-NBA") +
theme(plot.title = element_text(hjust=0.5)) +
  scale_fill_manual(values = c("#EF3B24", "#007AC1"))
```

##Simulations
```{r}
final_data %>%
  filter(Player == "Luka Doncic") %>%
  dplyr::select(Player, predicted)
doncic <-final_data %>%
  group_by(Player) %>%
  mutate(first_year = min(Year.End))
doncic <- doncic %>%
  filter(Year.End == first_year & predicted >= 0.2161168)
final_data %>%
  filter(Player == "Karl-Anthony Towns") %>%
  dplyr::select(Player, Age, predicted, All.NBA.TEAM.Yes...No)
kat <- final_data %>%
  filter(Age == 23 & All_NBA_Count == 1 & predicted >= 0.6854132)
final_data %>%
  filter(Player == "Kyrie Irving") %>%
  dplyr::select(Player, Age, predicted, All.NBA.TEAM.Yes...No)
kyrie <- final_data %>%
  filter(Age == 26 & All_NBA_Count == 2)
final_data %>%
  filter(Player == "Stephen Curry") %>%
  dplyr::select(Player, Age, predicted, All.NBA.TEAM.Yes...No)
curry <- final_data %>%
  filter(Age == 30 & All_NBA_Count == 6)
```

```{r}
doncic
luka_doncic<- final_data %>%
  filter(Player %in% doncic$Player & Player != "Ben Simmons" & Player != "Trae Young")
karl_anthony_towns <- final_data %>%
   filter(Player %in% kat$Player)
kyrie_irving <- final_data %>%
   filter(Player %in% kyrie$Player)
steph_curry <- final_data %>%
   filter(Player %in% curry$Player)
```

```{r}
doncic_bootstrap <- luka_doncic %>%
  group_by(Age) %>%
  generate(reps = 100, type = "bootstrap")
kat_bootstrap <- karl_anthony_towns %>%
  group_by(Age) %>%
  generate(reps = 100, type = "bootstrap")
kyrie_bootstrap <- kyrie_irving %>%
  group_by(Age) %>%
  generate(reps = 100, type = "bootstrap")
steph_bootstrap <- steph_curry %>%
  group_by(Age) %>%
  generate(reps = 100, type = "bootstrap")
```

```{r}
doncic_max <- doncic_bootstrap %>%
  group_by(Player) %>%
  filter(All.NBA.TEAM.Yes...No == "Yes") %>%
  summarise(max_age = max(Age))
doncic_max %>%
  summarise(mean = mean(max_age), sd = sd(max_age), q1 = quantile(max_age, 0.25), q3 = quantile(max_age, 0.75))
sim1 <- doncic_bootstrap %>%
  filter(Age >= 31	& Age <= 34) %>%
  summarise(mean_doncic = mean(predicted))

kat_max <- kat_bootstrap %>%
  group_by(Player) %>%
  filter(All.NBA.TEAM.Yes...No == "Yes") %>%
  summarise(max_age = max(Age))
kat_max %>%
  summarise(mean = mean(max_age), sd = sd(max_age), q1 = quantile(max_age, 0.25), q3 = quantile(max_age, 0.75))
sim2 <- kat_bootstrap %>%
  filter(Age >= 31 & Age <= 34) %>%
  summarise(mean_kat = mean(predicted))


kyrie_max <- kyrie_bootstrap %>%
  group_by(Player) %>%
  filter(All.NBA.TEAM.Yes...No == "Yes") %>%
  summarise(max_age = max(Age))
kyrie_max %>%
  summarise(mean = mean(max_age), sd = sd(max_age), q1 = quantile(max_age, 0.25), q3 = quantile(max_age, 0.75))
sim3 <- kyrie_bootstrap %>%
  filter(Age >= 31 & Age <= 34) %>%
  summarise(mean_kyrie = mean(predicted))


steph_max <- steph_bootstrap %>%
  group_by(Player) %>%
  filter(All.NBA.TEAM.Yes...No == "Yes") %>%
  summarise(max_age = max(Age))
steph_max %>%
  summarise(mean = mean(max_age), sd = sd(max_age), q1 = quantile(max_age, 0.25), q3 = quantile(max_age, 0.75))
sim4 <- steph_bootstrap %>%
  filter(Age >= 31 & Age <= 34) %>%
  summarise(mean_steph = mean(predicted))
```

```{r}
sim1 <- sim1 %>%
  mutate(difference_doncic = mean_doncic - 0)
sim2 <- sim2 %>%
  mutate(difference_kat = mean_kat - 1)
sim3 <- sim3 %>%
  mutate(difference_kyrie = mean_kyrie - 2)
sim4 <- sim4 %>%
  mutate(difference_steph = mean_steph - 6)
combined <- Reduce(function(x,y) merge(x,y,by="replicate",all=TRUE) ,list(sim1,sim2,sim3,sim4))
combined <- combined %>%
  group_by(replicate) %>%
  mutate(highest = case_when(
    difference_doncic > difference_kat & difference_doncic > difference_kyrie & difference_doncic > difference_steph ~ "Luka",
    difference_kat > difference_doncic & difference_kat > difference_kyrie & difference_kat > difference_steph ~ "KAT",
    difference_kyrie > difference_doncic & difference_kyrie > difference_kat & difference_kyrie > difference_steph ~ "Kyrie",
    difference_steph > difference_doncic & difference_steph > difference_kat & difference_steph > difference_kyrie ~ "Steph"
      ))

combined %>%
  group_by(highest) %>%
  summarise(proportion = n()/100)
sim1 %>%
  summarise(total = mean(difference_doncic))
sim2 %>%
  summarise(total = mean(difference_kat))
sim3 %>%
  summarise(total = mean(difference_kyrie))
sim4 %>%
  summarise(total = mean(difference_steph))
```



